In [76]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

print("download dataset")
df = pd.read_csv('Students Performance Dataset.csv')

download dataset

In [69]:
#первичный осмотр
df.head(20)

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
0,S1000,Omar,Williams,student0@university.com,Female,22,Mathematics,97.36,40.61,59.61,73.69,53.17,73.4,62.84,59.8865,F,10.3,Yes,No,Master's,Medium,1,5.9
1,S1001,Maria,Brown,student1@university.com,Male,18,Business,97.71,57.27,74.00,74.23,98.23,88.0,98.23,81.9170,B,27.1,No,No,High School,Low,4,4.3
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Engineering,99.52,41.84,63.85,85.85,50.00,4.7,91.22,67.7170,D,12.4,Yes,No,High School,Low,9,6.1
3,S1003,Omar,Williams,student3@university.com,Female,24,Engineering,90.38,45.65,44.44,68.10,66.27,4.2,55.48,51.6535,F,25.5,No,Yes,High School,Low,8,4.9
4,S1004,John,Smith,student4@university.com,Female,23,CS,59.41,53.13,61.77,67.66,83.98,64.3,87.43,71.4030,C,13.3,Yes,No,Master's,Medium,6,4.5
5,S1005,Liam,Brown,student5@university.com,Male,21,Mathematics,60.60,70.21,64.48,87.85,52.26,54.8,67.65,68.0900,D,25.3,Yes,No,NaN,Medium,6,5.6
6,S1006,Ahmed,Jones,student6@university.com,Male,24,Business,67.01,90.85,93.74,89.00,54.17,15.5,87.51,82.8575,B,22.1,Yes,No,Bachelor's,High,2,4.0
7,S1007,Ahmed,Smith,student7@university.com,Male,19,Engineering,65.91,91.72,59.47,50.72,53.83,54.8,90.04,71.3685,C,16.7,Yes,Yes,NaN,Low,5,7.8
8,S1008,Omar,Smith,student8@university.com,Female,21,CS,97.83,76.97,62.75,57.19,79.08,97.4,57.57,65.8605,D,18.1,No,Yes,PhD,High,9,4.8
9,S1009,Sara,Smith,student9@university.com,Female,22,Business,89.45,95.69,86.97,60.65,94.80,63.1,83.09,82.7555,B,9.4,Yes,No,NaN,High,8,7.1
10,S1010,John,Smith,student10@university.com,Female,23,Business,86.20,70.00,85.54,67.58,77.77,44.9,93.14,79.9860,C,7.9,Yes,Yes,High School,Low,4,8.2
11,S1011,Omar,Williams,student11@university.com,Female,20,Mathematics,59.30,93.34,87.90,64.57,80.18,82.8,66.17,77.6705,C,22.9,Yes,No,NaN,Low,7,8.6
12,S1012,John,Davis,student12@university.com,Male,21,Engineering,95.48,67.24,97.23,83.43,67.30,21.3,54.02,70.9090,C,26.2,No,No,NaN,Medium,9,6.8
13,S1013,John,Williams,student13@university.com,Male,18,Business,91.39,56.63,87.73,91.41,50.94,41.4,51.36,66.7105,D,23.0,No,No,PhD,Medium,5,7.9
14,S1014,Liam,Williams,student14@university.com,Male,19,CS,58.18,94.98,64.46,59.60,51.08,52.8,55.50,63.7000,D,27.8,No,Yes,Bachelor's,High,2,6.3
15,S1015,Ahmed,Jones,student15@university.com,Male,18,CS,93.56,63.28,89.29,78.15,94.42,50.5,50.21,70.5670,C,27.3,Yes,No,Bachelor's,Low,2,6.5
16,S1016,Maria,Jones,student16@university.com,Female,21,Business,63.61,70.20,70.52,68.39,55.13,92.1,66.35,68.4415,D,24.5,No,Yes,High School,High,8,6.7
17,S1017,Liam,Davis,student17@university.com,Female,23,CS,54.04,59.73,56.66,75.29,99.99,29.3,64.97,65.3730,D,27.5,No,No,Bachelor's,Medium,8,7.4
18,S1018,Liam,Jones,student18@university.com,Male,20,Business,82.84,79.77,58.18,81.04,58.22,5.7,55.52,61.4295,D,9.2,Yes,Yes,High School,High,8,7.3
19,S1019,John,Johnson,student19@university.com,Male,20,CS,82.69,99.70,53.43,94.68,83.73,91.6,82.56,80.2355,B,23.3,No,Yes,Master's,Low,5,7.9

In [70]:
print("\nобщая информация")
df.info()

общая информация
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  5000 non-null   str
 1   First_Name                  5000 non-null   str
 2   Last_Name                   5000 non-null   str
 3   Email                       5000 non-null   str
 4   Gender                      5000 non-null   str
 5   Age                         5000 non-null   int64
 6   Department                  5000 non-null   str
 7   Attendance (%)              5000 non-null   float64
 8   Midterm_Score               5000 non-null   float64
 9   Final_Score                 5000 non-null   float64
 10  Assignments_Avg             5000 non-null   float64
 11  Quizzes_Avg                 5000 non-null   float64
 12  Participation_Score         5000 non-null   float64
 13  Projects_Score              5000 non-null   float64
 14  Total_Score                 5000 non-null   float64
 15  Grade                       5000 non-null   str
 16  Study_Hours_per_Week        5000 non-null   float64
 17  Extracurricular_Activities  5000 non-null   str
 18  Internet_Access_at_Home     5000 non-null   str
 19  Parent_Education_Level      3975 non-null   str
 20  Family_Income_Level         5000 non-null   str
 21  Stress_Level (1-10)         5000 non-null   int64
 22  Sleep_Hours_per_Night       5000 non-null   float64
dtypes: float64(10), int64(2), str(11)
memory usage: 898.6 KB

In [77]:
print("\nописание датасета")
df.describe()

описание датасета

,Age,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Study_Hours_per_Week,Stress_Level (1-10),Sleep_Hours_per_Night
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,21.048400,75.356076,70.701924,69.546552,74.956320,74.836214,49.963720,74.78305,71.652097,17.521140,5.507200,6.514420
std,1.989786,14.392716,17.436325,17.108996,14.404287,14.423848,28.989785,14.54243,7.230097,7.193035,2.886662,1.446155
min,18.000000,50.010000,40.000000,40.010000,50.000000,50.000000,0.000000,50.00000,50.602000,5.000000,1.000000,4.000000
25%,19.000000,62.945000,55.707500,54.697500,62.340000,62.357500,25.075000,61.97000,66.533875,11.500000,3.000000,5.300000
50%,21.000000,75.670000,70.860000,69.485000,75.090000,74.905000,49.600000,74.54000,71.696250,17.400000,6.000000,6.500000
75%,23.000000,87.862500,85.760000,83.922500,87.352500,87.292500,75.500000,87.63000,76.711625,23.700000,8.000000,7.800000
max,24.000000,100.000000,99.990000,99.980000,99.990000,99.990000,100.000000,100.00000,95.091500,30.000000,10.000000,9.000000

In [78]:
print("\nколичество объектов каждого класса")
print(df['Grade'].value_counts())
print("\nбаланс классов")
print(df['Grade'].value_counts(normalize=True) * 100)

количество объектов каждого класса
Grade
C    2307
D    1760
B     638
F     279
A      16
Name: count, dtype: int64

баланс классов
Grade
C    46.14
D    35.20
B    12.76
F     5.58
A     0.32
Name: proportion, dtype: float64

In [79]:
print("\nколичество пропусков")
missing_values = df.isnull().sum().sort_values(ascending=False)
print(missing_values[missing_values > 0])

#заполнение пропусков медиантой, тк если они появятся, их будет мало
from sklearn.impute import SimpleImputer
if df.isnull().sum().sum() > 0: 
    imputer = SimpleImputer(strategy='median')
    numeric_cols = df.select_dtypes(include=['number']).columns

    df[numeric_cols] = imputer.fit_transform(df[numeric_cols])
    print("пропуски заполнены медианой")
else:
    print("пропусков нет")

количество пропусков
Parent_Education_Level    1025
dtype: int64
пропуски заполнены медианой

In [85]:
print(f"\nпроверка на дубликаты {df.duplicated().sum()}")

print("\nкатегориальные признаки")
for col in ['Gender', 'Department', 'Parent_Education_Level', 'Family_Income_Level']:
    if col in df.columns:
        print(f"{col}: {df[col].nunique()}")

проверка на дубликаты 0

категориальные признаки
Gender: 2
Department: 4
Parent_Education_Level: 4
Family_Income_Level: 3